name: Bug Report 🐞
description: Report a reproducible bug.
title: '[BUG] '
labels:
  - bug

body:
  - type: markdown
    attributes:
      value: |
        ### Reporting a new bug 🐞
        🔍  Before opening a new issue please search existing issues at https://github.com/eclipse/jnosql/issues
        🤔  To make it easier for us to help you, please include as much useful information as possible.

        Please test using the latest JNoSQL release to make sure your issue has not already been fixed: https://github.com/eclipse/jnosql/releases
  - type: dropdown
    id: project
    attributes:
      label: Which JNoSQL project the issue refers to?
      description: Please tell us which JNoSQL project this issue refers to
      options:
        - "JNoSQL (Core)"
        - "JNoSQL Databases"
        - "JNoSQL Extensions"
    validations:
      required: true
  - type: textarea
    id: bug_description
    validations:
      required: true
    attributes:
      label: Bug description
      description: Please provide a clear and concise description of what the bug is. Include screenshots if needed.

  - type: input
    id: jnosql_version
    attributes:
      label: JNoSQL Version
      description: Describe the JNoSQL version used
      value: JNoSQL version
    validations:
      required: true

  - type: textarea
    id: repro_steps
    validations:
      required: true
    attributes:
      label: Steps To Reproduce
      description: Provide a detailed list of steps that reproduce the issue.
      placeholder: |
        1.
        2.

  - type: textarea
    id: expected_results
    attributes:
      label: Expected Results
      description: Describe what you expected to happen.

  - type: textarea
    id: code_example
    attributes:
      label: Code example, screenshot, or link to a repository
      description: |
        Please provide a link to a repository on GitHub, or provide a minimal code example that reproduces the problem.
        You may provide a screenshot of the application if you think it is relevant to your bug report.
        Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve
