name: Feature request 💡
description: Suggest a new idea for Eclipse JNoSQL.
labels: 'enhancement'

body:
  - type: markdown
    attributes:
      value: |
        ### Requesting a new feature 💡
        🔍  Before opening a new issue please search existing issues at https://github.com/eclipse/jnosql/issues
        🤔  To make it easier for us to help you, please include as much useful information as possible.
  - type: dropdown
    id: project
    attributes:
      label: Which JNoSQL project the issue refers to?
      description: Please tell us which JNoSQL project this issue refers to
      options:
        - "JNoSQL (Core)"
        - "JNoSQL Databases"
        - "JNoSQL Extensions"
    validations:
      required: true
  - type: textarea
    id: use_case
    attributes:
      label: Use case
      description: Please tell us the problem you are running into that led to you wanting a new feature.
      placeholder: |
        Is your feature request related to a problem? Please give a clear and concise description of what the problem is.
        Describe alternative solutions you've considered.
    validations:
      required: true

  - type: textarea
    id: feature_proposal
    attributes:
      label: Feature proposal
      description: Briefly but precisely describe what you would like Eclipse JNoSQL to be able to do.
      placeholder: |
        Consider attaching images and examples showing what you are imagining.
    validations:
      required: true